spring.datasource.username=admin
spring.datasource.password=thefull134679!!

google.cloud.vision.credentials.path=file:/opt/keys/the-full-ocr-project-f7202d1e7284.json

documentai.project.id=the-full-ocr-project
documentai.location=us
#documentai.processor.id=589cbd30ec67164

openai.api.key=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
