spring.datasource.username=root
spring.datasource.password=Sk20150115!

google.cloud.vision.credentials.path=classpath:keys/the-full-ocr-project-f7202d1e7284.json

documentai.project.id=the-full-ocr-project
documentai.location=us
#documentai.processor.id=589cbd30ec67164

openai.api.key=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

# Welstory FD API - local
welstory.api.base-url=http://123.37.36.174:80
welstory.api.token-url=http://123.37.36.174:80/oauth/2.0/token
welstory.api.revoke-url=http://123.37.36.174:80/oauth/2.0/revoke
welstory.api.realtime-item-url=http://123.37.36.174:80/fdapi/service/payer-realtime-item
welstory.api.access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImI0MDU2YzVhLTZmZGYtNDNmNC05YmJhLWRjZWNlYWMxMTZmMCIsIm5iZiI6MTc4NTMwNjg0MCwiaXNzIjoidW5vZ3ciLCJleHAiOjE3ODc4OTg4NDAsImlhdCI6MTc4NTMwNjg0MCwianRpIjoibDd4eGFIMHhkME5pejh3blF4QmgzSEFjeWxiRkxlcnRqVTlqIiwic2lkIjoiOWM0NTY1NGItNzJlNC00ZmZmLTlhNDMtMDc1NjVkMWZkYTNhIn0.BeRXqaVjIBZJJgTwHM2d_nZr-qcJX30GjLuFyqEInNRJp_3t4bgnNJBbDo7kuvjv-NqCnl73SmQvU0Td3nHxzw
welstory.api.client-id=l7xxaH0xd0Niz8wnQxBh3HAcylbFLertjU9j
welstory.api.client-secret=3YfTV2C6uRyJ9DX6yVZDGlIjINAbFYAO
welstory.api.timeout-seconds=10
welstory.websocket.enabled=false
welstory.websocket.url=wss://welws-stg.welstory.com/websocket