package com.example.demo.service;
import java.util.List; import java.util.Map; import java.util.UUID; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import com.example.demo.mapper.ProcurementCrudMapper;
@Service public class ProcurementCrudService {
 private final ProcurementCrudMapper m; public ProcurementCrudService(ProcurementCrudMapper m){this.m=m;}
 public List<Map<String,Object>> analysis(Map<String,Object>p){required(p,"account_id","table_id");return m.analysis(p);} public List<Map<String,Object>> shortages(Map<String,Object>p){required(p,"account_id","table_id");return m.shortages(p);} public List<Map<String,Object>> carts(Map<String,Object>p){required(p,"account_id");return m.carts(p);} public List<Map<String,Object>> cartItems(Map<String,Object>p){required(p,"procurement_cart_id");return m.cartItems(p);} public List<Map<String,Object>> orders(Map<String,Object>p){required(p,"account_id");return m.orders(p);} public List<Map<String,Object>> orderItems(Map<String,Object>p){required(p,"purchase_order_id");return m.orderItems(p);}
 public Map<String,Object> createCart(Map<String,Object>b){required(b,"account_id");m.insertCart(b);return ok(b.get("procurement_cart_id"));} public Map<String,Object> updateCart(Map<String,Object>b){required(b,"procurement_cart_id");return changed(m.updateCart(b),b.get("procurement_cart_id"));} @Transactional public Map<String,Object> deleteCart(Map<String,Object>b){required(b,"procurement_cart_id");m.deleteCartItems(b);return changed(m.deleteCart(b),b.get("procurement_cart_id"));}
 public Map<String,Object> createCartItem(Map<String,Object>b){required(b,"procurement_cart_id","account_ingredient_product_id","source_type");m.insertCartItem(b);return ok(b.get("procurement_cart_item_id"));} public Map<String,Object> updateCartItem(Map<String,Object>b){required(b,"procurement_cart_item_id");return changed(m.updateCartItem(b),b.get("procurement_cart_item_id"));} public Map<String,Object> deleteCartItem(Map<String,Object>b){required(b,"procurement_cart_item_id");return changed(m.deleteCartItem(b),b.get("procurement_cart_item_id"));}
 @Transactional public Map<String,Object> createFromMealPlan(Map<String,Object>b){required(b,"account_id","table_id");m.insertCart(b);b.put("source_id",b.get("table_id"));int count=m.insertMealShortages(b);return Map.of("code",200,"message","success","procurement_cart_id",b.get("procurement_cart_id"),"item_count",count);}
 public Map<String,Object> createOrder(Map<String,Object>b){required(b,"account_id","supplier_id","client_ord","requested_delivery_date");b.putIfAbsent("purchase_order_id",UUID.randomUUID().toString());m.insertOrder(b);return ok(b.get("purchase_order_id"));} public Map<String,Object> updateOrder(Map<String,Object>b){required(b,"purchase_order_id");return changed(m.updateOrder(b),b.get("purchase_order_id"));} @Transactional public Map<String,Object> deleteOrder(Map<String,Object>b){required(b,"purchase_order_id");m.deleteOrderItems(b);return changed(m.deleteOrder(b),b.get("purchase_order_id"));}
 public Map<String,Object> createOrderItem(Map<String,Object>b){required(b,"purchase_order_id","client_ord_item","account_ingredient_product_id","supplier_item_code","order_qty","order_unit","base_qty_per_order_unit","base_unit","unit_price_snapshot","line_amount");m.insertOrderItem(b);return ok(b.get("purchase_order_item_id"));} public Map<String,Object> updateOrderItem(Map<String,Object>b){required(b,"purchase_order_item_id");return changed(m.updateOrderItem(b),b.get("purchase_order_item_id"));} public Map<String,Object> deleteOrderItem(Map<String,Object>b){required(b,"purchase_order_item_id");return changed(m.deleteOrderItem(b),b.get("purchase_order_item_id"));}
 private void required(Map<String,Object>b,String...fs){for(String f:fs)if(b.get(f)==null||b.get(f).toString().isBlank())throw new IllegalArgumentException(f+" is required.");} private Map<String,Object>ok(Object id){return Map.of("code",200,"message","success","id",id);} private Map<String,Object>changed(int n,Object id){if(n==0)throw new IllegalArgumentException("Target row was not found or is not editable.");return ok(id);}
}
